/// BASE URL
const String BASE_URL = "http://144.24.64.142:8080";

/// STORAGE KEY
const String ACCESS_TOKEN_STORAGE_KEY = "ACCESS_TOKEN";
const String REFRESH_TOKEN_STORAGE_KEY = "REFRESH_TOKEN";

const int MAX_SIGNUP_STEP = 5; // 회원가입 단계